#! /usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use App\TabularCommand;

require 'vendor/autoload.php';

$app = new Application('Laracasts Tabular Demo', '1.0');

$app->add(new TabularCommand);

$app->run();