#! /usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use App\GreetingCommand;

require 'vendor/autoload.php';

$app = new Application('Laracasts Demo', '1.0');

$app->add(new GreetingCommand);

$app->run();